version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: client_container
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    networks:
      - web

networks:
  web:
    external: true